### ISSUE TITLE
gRPC message exceeds maximum size 4194304: 4268579

### ISSUE THREAD

**Issue by NiasSt90** [AxonIQ/axon-server-se#102]
```
axon_1_b7193925574e | io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304: 4268579
axon_1_b7193925574e |   at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.27.2.jar:1.27.2]
axon_1_b7193925574e |   at io.grpc.internal.MessageDeframer.processHeader(MessageDeframer.java:387) ~[grpc-core-1.27.2.jar:1.27.2]
axon_1_b7193925574e |   at io.grpc.internal.MessageDeframer.deliver(MessageDeframer.java:267) ~[grpc-core-1.27.2.jar:1.27.2]
axon_1_b7193925574e |   at io.grpc.internal.MessageDeframer.request(MessageDeframer.java:161) ~[grpc-core-1.27.2.jar:1.27.2]
axon_1_b7193925574e |   at io.grpc.internal.AbstractStream$TransportState.requestMessagesFromDeframer(AbstractStream.java:205) ~[grpc-core-1.27.2.jar:1.27.2]
axon_1_b7193925574e |   at io.grpc.netty.NettyServerStream$Sink$1.run(NettyServerStream.java:112) ~[grpc-netty-1.27.2.jar:1.27.2]
axon_1_b7193925574e |   at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
axon_1_b7193925574e |   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
axon_1_b7193925574e |   at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:388) ~[netty-transport-native-epoll-4.1.42.Final-linux-x86_64.jar:4.1.42.Final]
axon_1_b7193925574e |   at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
axon_1_b7193925574e |   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
axon_1_b7193925574e |   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
axon_1_b7193925574e |   at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

i found no option in the documentation to increase these value on the server...
In my case storing the snapshots generate these large messages.

**Comment by MGathier** [comment]
gRPC has a default maximum message size of 4194304. If you want to send larger messages you need to set 
axon.axonserver.max-message-size 
to a larger value in the client application and 
axoniq.axonserver.max-message-size for AxonServer.

**Comment by NiasSt90** [comment]
> gRPC has a default maximum message size of 4194304. If you want to send larger messages you need to set
> axon.axonserver.max-message-size
> to a larger value in the client application and
> axoniq.axonserver.max-message-size for AxonServer.

thanks, tried and it works as expected.
