### ISSUE TITLE
Add flow control to loading events belonging to an aggregate

### ISSUE THREAD

**Issue by jvanderkallen** [AxonIQ/axon-server-se#196]
**Current Behavior**
The method `EventStore#listAggregateEvents` does not offer flow control. This is not a problem if you have an aggregate with a small number of events or if you have an aggregate with a large number of events with snapshotting enabled. However, if you want to recreate snapshots for aggregates with a large number of events then this can cause the application to get flooded by events. This can result in out of memory errors. Recreating snapshots may be necessary if you have made changes to an aggregate that are not backwards compatible with existing snapshots and you do not want to or cannot use an upcaster.

I have done a test on an AWS EC2 instance: i3.large. This EC2 instance has 2 vCPUs and 15.25 GiB RAM. The machine was running Ubuntu 20.04.1 LTS. The test consisted of running an application which used version 4.4.3 of Axon Framework. I was using Axon Server Standard Edition v4.4.1 (Docker image axoniq/axonserver:4.4.1). The application had a max heap size of 6 GB (`-Xmx6g`). The test consisted of sending a command to an aggregate with 29.733.168 events. The command handler in the aggregate didn't do anything. The purpose was to hydrate the aggregate and trigger the creation of a snapshot. There were no snapshots in Axon Server for the aggregate.

I have observed two types of behavior. I have observed out of memory errors being thrown while the command is being processed. I have also observed that the command seemed to be processed successfully but the created snapshot had a sequence number which was much smaller (4 million instead 29 million) than the last sequence number.

Here are some of the out the errors I have seen in the log of the application:

```
2020-10-30 12:00:39.098  WARN  8451 --- [xecutorLoop-8-1] i.n.u.c.SingleThreadEventExecutor        : Unexpected exception from an event executor: 

java.lang.IllegalMonitorStateException: null
	at java.base/java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:149)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1302)
	at java.base/java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:439)
	at java.base/java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:465)
	at io.netty.util.concurrent.SingleThreadEventExecutor.takeTask(SingleThreadEventExecutor.java:256)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:64)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

2020-10-30 12:05:43.523 ERROR  8451 --- [worker-ELG-10-1] i.n.h.c.http2.DefaultHttp2Connection     : Caught Throwable from listener onGoAwayReceived.

java.lang.OutOfMemoryError: Java heap space

2020-10-30 12:05:43.525 ERROR  8451 --- [alina-utility-2] o.a.coyote.http11.Http11NioProtocol      : Error processing async timeouts

java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.coyote.AbstractProtocol.startAsyncTimeout(AbstractProtocol.java:615)
	at org.apache.coyote.AbstractProtocol$1.run(AbstractProtocol.java:598)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.iterator(ConcurrentHashMap.java:4627)
	at java.base/java.util.Collections$SetFromMap.iterator(Collections.java:5567)
	at org.apache.coyote.AbstractProtocol$2.run(AbstractProtocol.java:625)
	... 7 common frames omitted

2020-10-30 12:15:07.354 ERROR  8451 --- [MessageBroker-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.lang.OutOfMemoryError: Java heap space

2020-10-30 12:15:07.356  INFO  8451 --- [-172-31-8-218-0] i.a.a.connector.impl.ControlChannelImpl  : Connected instruction stream for context 'default'. Sending client identification
2020-10-30 12:15:07.360  INFO  8451 --- [localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoException: java.lang.OutOfMemoryError: Java heap space
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:138)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:131)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.OutOfMemoryError: Java heap space

2020-10-30 12:15:07.364 ERROR  8451 --- [ingScheduled-12] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.lang.OutOfMemoryError: Java heap space

2020-10-30 12:15:07.368 ERROR  8451 --- [ringScheduled-2] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.lang.OutOfMemoryError: Java heap space

2020-10-30 12:15:07.869  INFO  8451 --- [-172-31-8-218-1] i.a.a.connector.impl.ControlChannelImpl  : Connected instruction stream for context 'default'. Sending client identification
```

**Desired Behavior**
It must be possible to control the flow of events coming from Axon Server when an application is loading events belonging to an aggregate.

**Comment by abuijze** [comment]
Hi @jvanderkallen, just to be certain. The OutOfMemory Errors that you refer to, do they happen on the client or server-side? Do you have a stack trace you can share?

**Comment by jvanderkallen** [comment]
> Hi @jvanderkallen, just to be certain. The OutOfMemory Errors that you refer to, do they happen on the client or server-side? Do you have a stack trace you can share?

Hi, @abuijze. Yes, I was referring to the client side. I'll see if I can provide you with additional information. Stay tuned for that.
