### ISSUE TITLE
Possible bug in AxonServerQueryBus?

### ISSUE THREAD

**Issue by emvidi** [AxonIQ/axon-server-se#246]
Hi, I am getting an exception when using the QueryBus provided by the axon-server-se. The exception is thrown when using the subscriptionQuery.

This is the exception:

```
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021) ~[na:na]
	at org.axonframework.queryhandling.SimpleQueryBus.lambda$scatterGather$3(SimpleQueryBus.java:206) ~[axon-messaging-4.4.6.jar:4.4.6]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
	at org.axonframework.axonserver.connector.query.AxonServerQueryBus$QueryProcessingTask.run(AxonServerQueryBus.java:437) ~[axon-server-connector-4.4.6.jar:4.4.6]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na] 
```

and this is the code:

```
public Mono<AuthenticationResult> authenticate(final Email email, final RawPassword rawPassword) {
    
    log.info("[E6] authenticate");
    Assert.notNull(email, EXC_MSG_EMAIL_NOT_NULL);
    Assert.notNull(rawPassword, EXC_MSG_RAW_PASSWORD_NOT_NULL);
    AttemptAuthenticationCommandBuilder cmdBuilder = AttemptAuthenticationCommand.builder();
    cmdBuilder.rawPassword(rawPassword);
    FindAccountAfterAuthAttemptQueryBuilder qryBuilder = FindAccountAfterAuthAttemptQuery.builder();
    
    return
    emailRepo.findById(email)
             .map(EmailProjection::getAccountId)
             .map(cmdBuilder::accountId)
             .map(AttemptAuthenticationCommandBuilder::build)
             .subscribeOn(Schedulers.boundedElastic())
             .flatMap(cmd -> {
               UUID accountId = cmd.getAccountId();
               UUID commandId = cmd.getCommandId();
               FindAccountAfterAuthAttemptQuery query = qryBuilder.commandId(commandId)
                                                                  .accountId(accountId)
                                                                  .build();
               return
               qryGateway.subscriptionQuery(query, AccountProjection.class, AccountProjection.class)
                         .flatMap(r -> {
                           return
                           r.initialResult()
                            .thenEmpty(cmdGateway.send(cmd))
                            .thenMany(r.updates())
                            .next()
                            .flatMapIterable(AccountProjection::getAuthenticationAttempts)
                            .filter(aap -> aap.getCommandId().equals(commandId))
                            .switchIfEmpty(Mono.error(AuthenticationAttemptProjectionNotFound::new))
                            .next()
                            .map(AuthenticationAttemptProjection::getAuthenticationResult);
                         });
             })
             .timeout(Duration.ofMillis(200))
             .doOnError(e -> log.error("[E6][ERROR] {}", e));
  }
```
```
  @EventHandler
  void on(AuthenticationAttemptedEvent event, @Timestamp Instant created){
    log.info("[E6] on(AuthenticationAttemptedEvent)");

    UUID accountId = event.getAccountId();
    UUID commandId = event.getCommandId();
    AuthenticationResult authResult = event.getAuthenticationResult();
    AuthenticationAttemptProjectionBuilder builder = AuthenticationAttemptProjection.builder();
    builder.commandId(commandId);
    builder.authenticationResult(authResult);
    builder.created(created);
    AuthenticationAttemptProjection aap = builder.build();
    Predicate<FindAccountAfterAuthAttemptQuery> isMatch = query -> query.getCommandId().equals(commandId);
    accountRepo.findById(accountId)
               .switchIfEmpty(Mono.error(AccountProjectionNotFound::new))
               .map(account -> {account.getAuthenticationAttempts().add(aap); return account;})
               .flatMap(accountRepo::save)
               .doOnError(e -> log.error("[E6][ERROR] {}", e))
               .subscribe(account -> {
                 queryUpdateEmitter.emit(FindAccountAfterAuthAttemptQuery.class, isMatch, account);
               });
  }

  @QueryHandler
  CompletableFuture<AccountProjection> handle(FindAccountAfterAuthAttemptQuery query) {
    log.info("[E6] handle(FindAccountAfterAuthAttemptQuery)");
    UUID accountId = query.getAccountId();
    return accountRepo.findById(accountId).toFuture();
  }
```
Spring Boot: 2.3.8.RELEASE
Axon Server SE: 4.4.9
Axon Framework: 4.4.6
Axon-Mongo: 4.4
Axon-Reactor: 4.4.2

**Comment by emvidi** [comment]
No longer present in 4.4.10
